[build]
  # DŮLEŽITÉ: spusť build s presetem netlify
  command = "NITRO_PRESET=netlify npm run build"
  # Public assets z Nitro buildu
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "20"   # (18+ je OK; 20 je bezpečná volba)

# Všechno pošli do Nitro serverless funkce (SSR + /api/*)
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200